#!/bin/bash

generateDatabase(){
  if [ "$1" == "gd" ]; then 
    source .env
    #Exportar banco
    docker exec laradock_mysql_1 sh -c 'exec mysqldump -u root -proot jisa-express' > jisa-express.sql

    #Importar banco na clever cloud
    docker exec -i laradock_mysql_1 sh -c "mysql -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE" < jisa-express.sql


    exit 0
  fi
}

update(){
  if [ "$1" == "update" ]; then
    start=`date +%s`

    cd server
    npm run build 
    
    status=$?

    if [ "$status" != 0 ]; then 
      echo -e "\n\nErro build do app\n\n"
      exit 0
    fi

    git add .
    git commit -m "$2"
    git push
    ssh -t root@test.codificar.dev.br "\
      cd projects/jisa \
      && git pull \
      && source ~/.nvm/nvm.sh \
      && cd server \
      && npm i \
      && npm run build \
      && pm2 restart jisa --update-env
    "

    echo -e "\nhttps://test.codificar.dev.br \n"

    end=`date +%s`
    runtime=$((end-start))

    echo -e "Duração do Deploy: $runtime segundos.\n"
    exit 0
  fi
}

fixMysql(){
  if [ "$1" == "fixMysql" ]; then
    status=$(pgrep mysql | wc -l)
    
    if [ "$status" == 0 ]; then 
      echo 'up mysql'
      cd ~/projects/laradock
      docker-compose up -d mysql phpmyadmin
    fi

    exit

  fi
}

  # && cd server \
command=$1
message=$2

main(){

  generateDatabase $command
  update $command "$message"
  fixMysql $command
  echo -e "\nComando não encontrado :(\n"

}

main