#!/bin/bash

generateDatabase(){
  if [ "$1" == "gd" ]; then 
    source .env
    #Exportar banco
    docker exec laradock_mysql_1 sh -c 'exec mysqldump -u root -proot jisa-express' > jisa-express.sql

    #Importar banco na clever cloud
    docker exec -i laradock_mysql_1 sh -c "mysql -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE" < jisa-express.sql


    exit 0
  fi
}

deploy(){
  if [ "$1" == "deploy" ]; then
    ssh -t root@test.codificar.dev.br "\
      cd projects/csa \
      && git pull \
      && source ~/.nvm/nvm.sh \
      && cd server \
      && npm i \
      && npm run build \
      && pm2 restart escolapp --update-env \
      && cd ../../laradock \
    "
    exit 0
    #&& docker-compose up -d mysql phpmyadmin 
  fi
}

update(){
  if [ "$1" == "update" ]; then
    start=`date +%s`

    cd server
    npx tsc    
    status=$?

    if [ "$status" != 0 ]; then 
      echo -e "\n\nErro no build do server\n\n"
      exit 0
    fi
    cd ..

    cd web 
    npm run build 
    status=$?
      if [ "$status" != 0 ]; then 
      echo -e "\n\nErro build do web\n\n"
      exit 0
    fi
    cd ..

  #   cd test 
  #   npm test 
  #   status=$?

  #  if [ "$status" != 0 ]; then 
  #     echo -e "\nErro nos tests :(\n"
  #     exit 0
  #   fi

    git add .
    git commit -m "$2"
    git push
    ssh -t root@test.codificar.dev.br "\
      cd projects/csa \
      && git pull \
      && source ~/.nvm/nvm.sh \
      && cd server \
      && npm i \
      && npm run build \
      && pm2 restart csa --update-env
    "

    echo -e "\nhttps://test.codificar.dev.br \n"

    end=`date +%s`
    runtime=$((end-start))

    echo -e "Duração do Deploy: $runtime segundos.\n"
    exit 0
  fi
}

fixMysql(){
  if [ "$1" == "fixMysql" ]; then
    status=$(pgrep mysql | wc -l)
    
    if [ "$status" == 0 ]; then 
      echo 'up mysql'
      cd ~/projects/laradock
      docker-compose up -d mysql phpmyadmin
    fi

    exit

  fi
}

commit(){
  if [ "$1" == "commit" ]; then 
    git add .
    git commit -m "$2"
    git push
    exit 0
  fi
}

  # && cd server \
command=$1
message=$2

main(){

  generateDatabase $command
  update $command "$message"
  fixMysql $command
  commit $command "$message"
  deploy $command
  echo -e "\nComando não encontrado :(\n"

}

main