name: Deploy 

on:
  push:
    branches:
     - main

jobs:
  install:
    name: Install Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/packege-lock') }}

      - name: Install dependencies 
        run: cd server
        run: npm ci 
        run: ls -la 
  
