name: Deploy 

on:
  push:
    branches:
     - main

jobs:
  tests-backend:
    name: Tests backend
    runs-on: ubuntu-latest
    # needs: install 

    services:
      mysql:
        image: mysql 
        ports: 
          - '3306:3306'
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: csa
    env:
      DATABASE_URL: mysql://root:root@localhost/csa
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: cd server && npm ci

      - name: Database run push
        run: cd server && npx prisma db push
      
      - name: Database run seed 
        run: cd server && npx prisma db seed

      - name: Run unit tests 
        run:
          cd server &&
          ls -la &&  
          npx tsc &&
          npm test
        #&& npm test



  # - name: Restore node_modules
  #   uses: actions/cache@v3
  #   with:
  #     path: server/node_modules
  #     key: ${{ runner.os }}-${{ hashFiles('**/packege-lock') }}

  # - name: Create mysql
  #   uses: mirromutth/mysql-action@v1.1
  #   with: 
  #     mysql database: csa 
  #     mysql user: root 
  #     mysql password: root






