name: Deploy 

on:
  push:
    branches:
     - main

jobs:
  # install:
  #   name: Install Packages
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Cache node_modules
  #       uses: actions/cache@v3
  #       with:
  #         path: server/node_modules
  #         key: ${{ runner.os }}-${{ hashFiles('**/packege-lock') }}

  #     - name: Install dependencies 
  #       run: cd server && npm ci && ls -la
  
  tests-backend:
    name: Run test backend
    runs-on: ubuntu-latest
    # needs: install 
    steps:
      - name: list 
        run: cd server && mv .env-exemple  && ls -la

      # - name: Checkout
      #   uses: actions/checkout@v3

      # - name: Restore node_modules
      #   uses: actions/cache@v3
      #   with:
      #     path: server/node_modules
      #     key: ${{ runner.os }}-${{ hashFiles('**/packege-lock') }}

      # - name: Run unit tests 
      #   run: cd server && npx tsc && npm test










