name: Deploy push
on:
  push:
    branches:
     - main
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: test ls
        run: ls
      
      - name: test ola mundo
        run: |
          echo ola povo
