name: Deploy push
on:
  push:
    branches:
     - main
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: test connect server
        run:    ssh -t root@test.codificar.dev.br "\
          ls"
